import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
=======
import Header from "./components/Header";
import Footer from "./components/Footer";
>>>>>>> 04342a810ea5441727877f814c8d4fc9141799b1

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
=======
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F6EEE2] min-h-screen flex flex-col`}
      >
        <Header />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
>>>>>>> 04342a810ea5441727877f814c8d4fc9141799b1
      </body>
    </html>
  );
}
