import jsPDF from "jspdf";

export function generatePDF(itinerary, tripTitle = "My Trip") {
  const doc = new jsPDF();
  let yPos = 20;

  // Title
  doc.setFontSize(20);
  doc.text(tripTitle, 20, yPos);
  yPos += 15;

  // Trip info
  doc.setFontSize(12);
  doc.text(`Destination: ${itinerary.destination}`, 20, yPos);
  yPos += 8;
  doc.text(`Budget: €${itinerary.totalBudget} for ${itinerary.people} people`, 20, yPos);
  yPos += 8;
  doc.text(`Style: ${itinerary.style}`, 20, yPos);
  yPos += 15;

  // Days
  itinerary.days.forEach((day) => {
    // Day header
    doc.setFontSize(14);
    doc.setTextColor(79, 70, 229); // Indigo
    doc.text(`Day ${day.day}`, 20, yPos);
    yPos += 8;

    // Activities
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text("Activities:", 20, yPos);
    yPos += 5;
    day.activities.forEach((activity) => {
      doc.text(`  • ${activity}`, 25, yPos);
      yPos += 5;
    });

    // Meals
    doc.text("Meals:", 20, yPos);
    yPos += 5;
    day.meals.forEach((meal) => {
      doc.text(`  • ${meal}`, 25, yPos);
      yPos += 5;
    });

    // Cost
    doc.text(`Estimated cost per person: €${day.estimatedCost}`, 20, yPos);
    yPos += 12;

    // Page break if needed
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
  });

  // Recommended Places Section
  if (itinerary.recommendedPlaces && itinerary.recommendedPlaces.length > 0) {
    // Page break if needed
    if (yPos > 220) {
      doc.addPage();
      yPos = 20;
    }

    yPos += 5;
    doc.setFontSize(14);
    doc.setTextColor(162, 28, 175); // Purple
    doc.text("Recommended Places", 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    itinerary.recommendedPlaces.forEach((place) => {
      const typeIcon = place.type === "restaurant" ? "[Restaurant]" : 
                       place.type === "cafe" ? "[Cafe]" : 
                       place.type === "attraction" ? "[Attraction]" : 
                       place.type === "museum" ? "[Museum]" : 
                       place.type === "bar" ? "[Bar]" : 
                       place.type === "park" ? "[Park]" : 
                       place.type === "landmark" ? "[Landmark]" : "[Place]";
      
      doc.setFont(undefined, "bold");
      doc.text(`${typeIcon} ${place.name}`, 20, yPos);
      yPos += 5;
      
      if (place.description) {
        doc.setFont(undefined, "normal");
        doc.setFontSize(9);
        // Wrap long descriptions
        const lines = doc.splitTextToSize(place.description, 170);
        lines.forEach((line) => {
          doc.text(line, 25, yPos);
          yPos += 4;
        });
        doc.setFontSize(10);
      }
      yPos += 3;

      // Page break if needed
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
    });
  }

  // Hotels Section
  if (itinerary.hotels?.hotels && itinerary.hotels.hotels.length > 0) {
    if (yPos > 220) {
      doc.addPage();
      yPos = 20;
    }

    yPos += 5;
    doc.setFontSize(14);
    doc.setTextColor(14, 165, 233); // Blue
    doc.text("Accommodation Options", 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    itinerary.hotels.hotels.forEach((hotel) => {
      doc.setFont(undefined, "bold");
      doc.text(hotel.name, 20, yPos);
      yPos += 5;
      
      doc.setFont(undefined, "normal");
      if (hotel.pricePerNight) {
        doc.text(`€${hotel.pricePerNight}/night - ${hotel.type}`, 25, yPos);
        yPos += 5;
      }
      yPos += 2;
    });

    // Booking links
    if (itinerary.hotels.bookingLinks) {
      yPos += 3;
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text("Book at: Booking.com | Airbnb | Hostelworld", 20, yPos);
      yPos += 8;
    }
  }

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Travel Planner", 20, doc.internal.pageSize.height - 10);

  // Download
  doc.save(`${tripTitle.replace(/\s+/g, "_")}_itinerary.pdf`);
}
